site_name: SimpliML
site_dir: build_docs
repo_url: https://github.com/rajaddr/simpliml
site_description: ''

theme:
   name: readthedocs
nav:
  - SimpliML: index.md
  - Installation: install.md
  - Time Series: tsf.md
  - About: about.md